### ISSUE TITLE
No CMakeLists.txt files

### ISSUE THREAD

**Issue by Sawada-Naoko** [ashwath98/deepcharacters#1]
Dear @MarcHabermann and @ashwath98 ,

thank you for the amazing work.
I'm trying to install the Holoported Characters.
I noticed that there is no CMakeLists.txt file in "CustomTensorFlowCPPOperators/cmakeTF2Linux" and "CudaRenderer/cpp/cmakeTF2Linux".
Could you upload them?

Thanks for your help.

**Comment by ashwath98** [comment]
Hi @MistletoeNaoko, thanks for raising the issues.
I added the Cmakelists; I am sorry, for some reason, they were in git ignore and didn't go through initially 
please let us know if you face any more issues
-Ashwath
